# Generated by Django 4.0.2 on 2022-05-25 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoría')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre dela categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('patente', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Patente')),
                ('marca', models.CharField(max_length=20, verbose_name='Marca del vehículo')),
                ('modelo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Modelo del vehículo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
    ]
