# Generated by Django 4.0.4 on 2022-05-31 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='marca',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='categoria',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='modelo',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='patente',
            new_name='patent',
        ),
    ]
