# Generated by Django 4.0.4 on 2022-06-24 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customer_vehicle_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la ciudad')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de la ciudad')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre de la categoría'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.customer', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.city', verbose_name='Ciudad'),
        ),
    ]
