# Generated by Django 4.0.4 on 2022-07-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del Modelo')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre del modelo')),
            ],
        ),
    ]
