# Generated by Django 4.0.4 on 2022-06-24 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_marca_vehicle_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('rut', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='RUN')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='customer',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.customer'),
            preserve_default=False,
        ),
    ]
