# Generated by Django 4.0.4 on 2022-06-24 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_city_alter_category_name_alter_vehicle_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='rut',
            new_name='run',
        ),
    ]
