# Generated by Django 4.0.4 on 2022-07-12 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rest_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('patent', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Patente')),
                ('brand', models.CharField(max_length=20, verbose_name='Marca del vehículo')),
                ('model', models.CharField(blank=True, max_length=20, null=True, verbose_name='Modelo del vehículo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_category.category')),
            ],
        ),
    ]
