# Generated by Django 4.0.4 on 2022-07-12 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_vehicle', '0002_alter_vehicle_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=20, verbose_name='Modelo del vehículo'),
        ),
    ]
