# Generated by Django 4.0.4 on 2022-07-12 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_model', '0001_initial'),
        ('rest_vehicle', '0003_alter_vehicle_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_model.model'),
        ),
    ]
